paths:
  - ../
exclude_files: ~
layers:
  - name: Application
    collectors:
      - type: bool
        must:
          - type: className
            regex: App\\Dictionary\\Application\\.*
        must_not:
          - type: className
            regex: App\\Dictionary\\Application\\Dto

  - name: Domain
    collectors:
      - type: className
        regex: App\\Dictionary\\Domain\\.*

  - name: Infrastructure
    collectors:
      - type: className
        regex: App\\Dictionary\\Infrastructure\\.*

  - name: UI
    collectors:
      - type: className
        regex: App\\Dictionary\\UI\\.*

ruleset:
  UI:
    - Application

  Application:
    - Domain

  Domain: ~

  Infrastructure:
    - Domain